name       : kcompletion
version    : 5.105.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kcompletion-5.105.0.tar.xz : 6e76e822a8b4e49d3357958fd3880858a59ccf4defd45a0e248c57535788b981
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
