name       : kcompletion
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/kcompletion-5.38.0.tar.xz : 5c943799729e7ed8d101eb2e11a09a2616d6c13c33d3575b2e61667e0c2f2539
license    : LGPL-2.1
component  : programming
summary    : Powerful completion framework, including completion-enabled lineedit
    and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
