name       : kcompletion
version    : 5.63.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kcompletion-5.63.0.tar.xz : 4bc7458e44fe5fba0e18aa296236de4523acb47b51f73d5f0a8ca904def5ef81
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
