name       : kcompletion
version    : 5.69.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kcompletion-5.69.0.tar.xz : 02070a926d252ca8a29970764a39cf984e80e72a4260fe8086718e96c43c0e14
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
