name       : kcompletion
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/kcompletion-5.36.0.tar.xz : 377103eb36855e0bb971fc22c974f85792ee71a73e6705725047ccfe337320f2
license    : LGPL-2.1
component  : programming
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
