name       : kcompletion
version    : 5.45.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kcompletion-5.45.0.tar.xz : c84d95ef4bf3a1c3fbed04f8f2bf940a0904800ff96016224310c3124e051753
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit
    and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
