name       : kcompletion
version    : 5.48.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kcompletion-5.48.0.tar.xz : 9796e291d84a7d7e3ab560245b042d12239235d7beb8be2c6b26036f08ac3589
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
