name       : kcompletion
version    : 5.72.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kcompletion-5.72.0.tar.xz : c73259f91c569162d4ff4aa52df9e3c8da9c43a5a2f25daa5b7d0f9c622cb220
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
