name       : kcompletion
version    : 5.44.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kcompletion-5.44.0.tar.xz : 44c1546558817b54ba247c8e86c40fc0263fbbd35fa02547e8eadede6d9ec2bb
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
