name       : kcompletion
version    : 5.94.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kcompletion-5.94.0.tar.xz : 1ad13d41650bbe352b0c2ecfd8c059015f9441cbf7534a2bcc9ed17a3bfa6ea4
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
