name       : kcompletion
version    : 5.68.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kcompletion-5.68.0.tar.xz : 642d68b4c472e11a8861a61238297633be288bfd72c13547707754f1ae2be33a
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
