name       : kcompletion
version    : 5.42.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kcompletion-5.42.0.tar.xz : 0e448a1a05436988a836ec0f533c8cb71e955251ec0d4b7e0dbbcc06b6880c7b
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/Fix-KLineEdit.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
