name       : kcompletion
version    : 5.60.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kcompletion-5.60.0.tar.xz : d5afb075661dfe2da5e300bd73dee89f92736f39859be711f186310bed245f7c
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
