name       : kcompletion
version    : 5.43.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kcompletion-5.43.0.tar.xz : 2999af185dea2164b6943c9cabf2330e4cae4bea46863a1c3d66e86b04ffb618
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
