name       : kcompletion
version    : 5.74.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kcompletion-5.74.0.tar.xz : 5bec7f31bab8eb724bfb01690bd1585b43eccca4e37c80cc3729af2f7c7b2875
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
