name       : kcompletion
version    : 5.91.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/kcompletion-5.91.0.tar.xz : 2422485b10de631583b7e92e0778e5cf0c0ceec677bcd289cb7bc04c5441dfd0
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
