name       : kcompletion
version    : 5.28.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.28/kcompletion-5.28.0.tar.xz : 6e1ca1714294e5906700cbba72b11e6cf9692c7239ded5478b93f6638d8334fb
license    : LGPL-2.1
component  : programming
summary    : Powerful completion framework, including completion-enabled lineedit
    and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
