name       : kcompletion
version    : 5.65.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kcompletion-5.65.0.tar.xz : bdd7201940fa47ac1b62f6fcf7a12883abed44876ff729cb430c11d3868eb8ae
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
