name       : kcompletion
version    : 5.47.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kcompletion-5.47.0.tar.xz : 17001dcb7e036e248ab597ce14fc55f845faf59b9723de5b6d14a4b8c820bcf1
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
