name       : kcompletion
version    : 5.78.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kcompletion-5.78.0.tar.xz : a73972651b5230c8df2d5d7b463d48004b8fd6672bda164e834eec5345113fa9
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 -i $pkgfiles/fix-regression.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
