name       : kcompletion
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kcompletion-5.25.0.tar.xz : 6a8af0a084ce697f57382f16157b0c21e4287c809819611fb7e6171e7e149d4a
license    : LGPL-2.1
component  : desktop.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
