name       : kcompletion
version    : 5.75.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kcompletion-5.75.0.tar.xz : 409b2759b6ac476b16fd6b5efd78381e9a840bae041fef35285404d2b79eeeff
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
