name       : kcompletion
version    : 5.50.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kcompletion-5.50.0.tar.xz : 5fe538fc18c57f167cac95262f75d4c638b16408c0e9cc3250c6c12be6cc0ed8
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
