name       : kcompletion
version    : 5.58.0
release    : 29
source     :
    - https://download.kde.org/stable/frameworks/5.58/kcompletion-5.58.0.tar.xz : 4f5be9d3a70183e0580126c6395d34e3e4141d6e6f852f5f0bb578b20205f5dd
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
