name       : kcompletion
version    : 5.92.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kcompletion-5.92.0.tar.xz : 08f1525c6cee8babe399c941bb85d04be9dade0341d1d85c6beccd2e93dc7ceb
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
