name       : kcompletion
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/kcompletion-5.35.0.tar.xz : 26509e70737d853596ea830409277a8e0be5627767f736ad27f676d6857a74da
license    : LGPL-2.1
component  : programming
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kconfig-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
